node {
   def commit_id
   def app
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       app = docker.build("docker16264/docker-nodejs-demo:${commit_id}", '.')
     }
   }
   stage('docker push') {
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
      app.push()
      }
   }   
}
